DELIMITER //
CREATE PROCEDURE `CLIENTE_NOVO_VELHO` (CPF VARCHAR(20))
BEGIN
	DECLARE RESULTADO VARCHAR(20);
    DECLARE DT_NASCIMENTO DATE;
    SELECT DATA_DE_NASCIMENTO INTO DT_NASCIMENTO FROM TABELA_DE_CLIENTES WHERE CPF = CPF;
    IF DT_NASCIMENTO < '2000-01-01' THEN
		SET RESULTADO = 'CLIENTE VELHO';
    ELSE
		SET RESULTADO = 'CLIENTE NOVO';
    END IF;
    SELECT RESULTADO;
END//

CALL CLIENTE_NOVO_VELHO('1471156710');

-- IF Aninhado
DELIMITER //
DROP PROCEDURE IF EXISTS IF_ANINHADO;
CREATE PROCEDURE `IF_ANINHADO` (CODIGO VARCHAR(20))
BEGIN
	DECLARE PRECO FLOAT;
    DECLARE RESULTADO VARCHAR(30);
    SELECT PRECO_DE_LISTA INTO PRECO FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = CODIGO LIMIT 1;
    IF PRECO >= 12 THEN
		SET RESULTADO = 'ESSE É UM PRODUTO CARO';
	ELSEIF PRECO >= 7 AND PRECO < 12 THEN
		SET RESULTADO = 'ESSE É UM PRODUTO EM CONTA';
	ELSE
		SET RESULTADO = 'ESSE É UM PRODUTO BARATO';
	END IF;
    SELECT RESULTADO;
END//

CALL IF_ANINHADO('1037797');

-- controle de fluxo usando o CASE
DELIMITER //
DROP PROCEDURE IF EXISTS TIPO_SABOR;
CREATE PROCEDURE `TIPO_SABOR` (CODIGO VARCHAR(20))
BEGIN
	DECLARE SABOR VARCHAR(10);
    SELECT SABOR INTO SABOR FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = CODIGO;
    CASE SABOR
		WHEN 'Laranja' THEN SELECT 'Cítrico';
        WHEN 'Lima/Limão' THEN SELECT 'Cítrico';
        WHEN 'Morango/Limão' THEN SELECT 'Cítrico';
		WHEN 'Uva' THEN SELECT 'Neutro';
        WHEN 'Morango' THEN SELECT 'Neutro';
        
        ELSE
			SELECT 'Ácido';
    END CASE;
END//

CALL TIPO_SABOR('1000889');
SELECT DISTINCT CODIGO_DO_PRODUTO, SABOR FROM TABELA_DE_PRODUTOS;

-- EXERCÍCIOS
DELIMITER //
CREATE PROCEDURE `TESTA_NUMERO_NOTAS` (CPF VARCHAR(11))
BEGIN
	DECLARE RESULTADO VARCHAR(20);
	DECLARE QTDE_NOTAS INT;
    SELECT COUNT(*) CPF INTO QTDE_NOTAS FROM NOTAS_FISCAIS WHERE CPF = CPF;
    IF QTDE_NOTAS > 70 THEN
		SET RESULTADO = 'MUITA NOTA';
	ELSE
		SET RESULTADO = 'POUCA NOTA';
	END IF;
	SELECT RESULTADO;
END//

CALL TESTA_NUMERO_NOTAS('9283760794');

-- comparação de vendas em duas datas
DELIMITER //
CREATE PROCEDURE `Comparativo_Vendas`(DataInicial DATE, DataFinal DATE)
BEGIN
	DECLARE FaturamentoInicial FLOAT;
	DECLARE FaturamentoFinal FLOAT;
	DECLARE Variacao float;
    
	SELECT SUM(B.QUANTIDADE * B.PRECO) INTO FaturamentoInicial FROM 
	NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
	ON A.NUMERO = B.NUMERO
	WHERE A.DATA_VENDA = DataInicial;
	SELECT SUM(B.QUANTIDADE * B.PRECO) INTO FaturamentoFinal FROM 
	NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
	ON A.NUMERO = B.NUMERO
	WHERE A.DATA_VENDA = DataFinal ;
	SET Variacao = ((FaturamentoFinal / FaturamentoInicial) -1) * 100;
    
	IF Variacao > 10 THEN
		SELECT 'Verde';
	ELSEIF Variacao >= -10 AND Variacao <= 10 THEN
		SELECT 'Amarelo';
	ELSE
		SELECT 'Vermelho';
	END IF;   
END//