/*
	Fórmula para pegar um número aleatório entre um número mínimo e um máximo
    (RAND() * (MAX - MIN + 1) + MIN)
*/
-- A função floor é usada para retornar somente a parte inteira de um número
SELECT FLOOR(RAND() * (300 - 15 + 1) + 15) AS NÚMERO_ALEATÓRIO;

-- CRIANDO A FUNÇÃO QUE RETORNA UM NÚMERO ALEATÓRIO
DELIMITER //
CREATE FUNCTION `F_NUMERO_ALEATORIO` (MIN INT, MAX INT)
RETURNS INT
BEGIN
	DECLARE vRETORNO INT;
    SELECT FLOOR(RAND() * (MAX - MIN + 1) + MIN) INTO vRETORNO;
    
    RETURN vRETORNO;
END//

SELECT F_NUMERO_ALEATORIO(1, 10) AS NUMERO_ALEATÓRIO;

-- CRIANDO A FUNÇÃO QUE RETORNA UM CLIENTE ALEATÓRIO
DELIMITER //
CREATE FUNCTION `F_CLIENTE_ALEATORIO` ()
RETURNS VARCHAR(11)
BEGIN
	DECLARE vRETORNO VARCHAR(11);
    DECLARE NUM_MAX_CLIENTES INT;
    DECLARE NUM_ALEATORIO INT;
    
    SELECT COUNT(*) INTO NUM_MAX_CLIENTES FROM TABELA_DE_CLIENTES;
    
    SET NUM_ALEATORIO = F_NUMERO_ALEATORIO(1, NUM_MAX_CLIENTES);
    SET NUM_ALEATORIO = NUM_ALEATORIO - 1;
    
    SELECT CPF INTO vRETORNO FROM TABELA_DE_CLIENTES LIMIT NUM_ALEATORIO, 1;
    
    RETURN vRETORNO;
END//

SELECT F_CLIENTE_ALEATORIO() AS CLIENTE_ALEATÓRIO;

-- CRIANDO A FUNÇÃO QUE RETORNA UM PRODUTO ALEATÓRIO
DELIMITER //
CREATE FUNCTION `F_PRODUTO_ALEATORIO` ()
RETURNS VARCHAR(50)
BEGIN
	DECLARE vRETORNO VARCHAR(50);
    DECLARE NUM_MAX_PRODUTOS INT;
    DECLARE NUM_ALEATORIO INT;
    
    SELECT COUNT(*) INTO NUM_MAX_PRODUTOS FROM TABELA_DE_PRODUTOS;
    
    SET NUM_ALEATORIO = F_NUMERO_ALEATORIO(1, NUM_MAX_PRODUTOS);
    SET NUM_ALEATORIO  = NUM_ALEATORIO - 1;
    
    SELECT NOME_DO_PRODUTO INTO vRETORNO FROM TABELA_DE_PRODUTOS LIMIT NUM_ALEATORIO, 1;
    
    RETURN vRETORNO;
END//

SELECT F_PRODUTO_ALEATORIO() AS PRODUTO_ALEATÓRIO;

-- CRIANDO A FUNÇÃO QUE RETORNA UM VENDEDOR ALEATÓRIO
DELIMITER //
CREATE FUNCTION `F_VENDEDOR_ALEATORIO` ()
RETURNS VARCHAR(100) 
BEGIN
	DECLARE vRETORNO VARCHAR(100);
    DECLARE NUM_MAX_VENDEDORES INT;
    DECLARE NUM_ALEATORIO INT;
    
    SELECT COUNT(*) INTO NUM_MAX_VENDEDORES FROM TABELA_DE_VENDEDORES;
    
    SET NUM_ALEATORIO = F_NUMERO_ALEATORIO(1, NUM_MAX_VENDEDORES);
    SET NUM_ALEATORIO = NUM_ALEATORIO - 1;
    
    SELECT NOME INTO vRETORNO FROM TABELA_DE_VENDEDORES LIMIT NUM_ALEATORIO, 1;
    
    RETURN vRETORNO;
END//

SELECT F_VENDEDOR_ALEATORIO() AS NOME_VENDEDOR;

/*
	Crie uma tabela chamada TABELA_ALEATORIOS
    Faça uma Stored Procedure chamada TABELA_NUMEROS que use um loop para gravar
    nesta tabela 100 números aleatórios entre 0 e 1000.
    Depois liste numa consulta esta tabela
*/
CREATE TABLE TABELA_ALEATORIOS(NUMERO INT);

DELIMITER //
DROP PROCEDURE IF EXISTS TABELA_NUMEROS;
CREATE PROCEDURE `TABELA_NUMEROS` (MIN INT, MAX INT)
BEGIN
	DECLARE CONTADOR INT;
    DECLARE vNUMERO INT;
    DELETE FROM TABELA_ALEATORIOS;
    
    SET CONTADOR = MIN;
    
    WHILE CONTADOR <= 100
    DO
		SELECT FLOOR(RAND() * (MAX - MIN + 1) + MIN) INTO vNUMERO;
		INSERT INTO TABELA_ALEATORIOS (NUMERO)
        VALUES
        (vNUMERO);
        SET CONTADOR = CONTADOR + 1;
	END WHILE;
    SELECT * FROM TABELA_ALEATORIOS;
END//

CALL TABELA_NUMEROS(0, 1000);